---
title: "Module 1.2"
subtitle: "R, RStudio and Quarto"
format: html
execute: 
  echo: true
  message: false
  warning: false
---



## Example: Make a map!

```{r echo=FALSE}
library(leaflet)
leaflet() %>% 
  addTiles() %>%   # Add default OpenStreetMap map tiles
  addMarkers(lat = 38.90243843683386, lng =  -77.0443814477152, 
             label = "Elliott School of International Affairs")
```


## Example: Plotting Democracy Over Time

```{r echo=FALSE}
# For nice colors that work for color blind
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

library(vdemdata)
library(ggplot2)
library(tidyverse)
# We will use the data called vdem
vdem %>%
  # and then we are going to filter out and only use France and India
  filter(country_name == "France" | country_name == "India") %>%
  # and then we are going to only use years since 1850
  filter(year > 1849) %>% 
    # and then we are going to use this filtered data to make a plot
    #with democracy on the y axis and year on the x
    # we want this plot to use different colors for each country
    ggplot(., aes(y = v2x_polyarchy, x = year, color=country_name)) +
      geom_line() +
      theme_minimal() +
      xlab("Year") +
      ylab("Electoral Democracy Index") +
      ggtitle("Electoral Democracy, 1850-2022") +
      geom_hline(yintercept = .5, linetype = "dashed", color = "grey") +
       scale_color_manual(name="Country", values=c("#E69F00", "#56B4E9")) +
      ylim(0, 1)
```

## Example: UN Voting Trends

```{r echo=FALSE, warning=FALSE}
# = c("tidyverse", "lubridate", "scales", "DT", "unvotes", "pacman")

library(tidyverse)
library(unvotes)
library(lubridate)
library(scales)
library(pacman)

unvotes <- un_votes %>%
  inner_join(un_roll_calls, by = "rcid") %>%
  inner_join(un_roll_call_issues, by = "rcid")

unvotes %>%
  # then filter out to only include the countries we want
  filter(country %in% c("South Africa", "United States", "France")) %>%
  # then make sure R understands the the year variable is a data
  mutate(year = year(date)) %>%
  # Then group the data by country and year
  group_by(country, year, issue) %>%
  # then take the average Yes votes for each country_year
  summarize(percent_yes = mean(vote == "yes")) %>%
  # then make a nice plot
  ggplot(mapping = aes(x = year, y = percent_yes, color = country)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "loess", se = FALSE) +
  facet_wrap(~issue) +
  scale_y_continuous(labels = percent) +
  scale_color_manual( values=c("#E69F00", "#56B4E9", "#009E73")) +
  labs(
    title = "Percentage of 'Yes' votes in the UN General Assembly",
    subtitle = "1946 to 2019",
    y = "% Yes",
    x = "Year",
    color = "Country"
  )
```