---
title: "Course Schedule"
tbl-colwidths: [5,10,20,20,25,5,5,5,5,5]
editor: visual
---

```{r}
#| label: setup
#| include: false
library(lubridate)

mon <- as_date("2023-08-28")
wed <- mon+days(2)

advdate <- function(day, week) {
  date <- (day + weeks(week))
  dm <- paste(month(date, label = TRUE)," ", day(date))
  return(dm)  
}
```

This page displays an outline of the topics, content, and assignments for the term. Each module starts on a Monday. There are no assignments due on Sundays.

::: column-screen-inset-right
|                        Module                         | Date                | Skills                                                    | Packages                                                     | Functions                                                                                                                                                                           |                                      Readings                                       |                                                                  Reference                                                                  |           Slides           |                                                                                             Videos                                                                                              |                                                                                                     Assignments                                                                                                      |
|:------:|--------|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|
| [GS](/modules/getting-started.html "Getting Started") | `r advdate(mon,0)`  | Course Intro                                              |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                                             |                            |                                                                                                                                                                                                 |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,0)`  | RStudio, Quarto                                           |                                                              |                                                                                                                                                                                     |                                                                                     |                        [ðŸ“–](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/ "project-oriented workflow")                         | [ðŸ–¥ï¸](slides/week-1.2.qmd)  |                                                                       [ðŸ–¥ï¸](https://youtu.be/gssjyyl7vxI "R and RStudio")                                                                        |                                                                                                                                                                                                                      |
|                                                       | `r advdate(mon,1)`  | No class, Labor Day                                       |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                                             |                            |                                                                                                                                                                                                 |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,1)`  | Quarto, GitHub Classroom                                  |                                                              |                                                                                                                                                                                     |                                                                                     |                                          [ðŸ“–](https://happygitwithr.com/ "Chaps 4, 6, 7, 9 & 12")                                           | [ðŸ–¥ï¸](slides/week-2.1.qmd)  |                                           [ðŸ–¥ï¸](https://youtu.be/c654j7aQjcg "Quarto")[ðŸ–¥ï¸](https://youtu.be/ApvMnAfQe8A "GitHub and GitHub Classroom")                                           |                                                                                                                                                                                                                      |
|     [1.1](/modules/module-1.1.html "Module 1.1")      | `r advdate(mon,2)`  | Read data into R                                          | `readr`, `dplyr`                                             | `read_csv()`, `glimpse()`                                                                                                                                                           |                                                                                     |                                 [ðŸ“–](https://r4ds.hadley.nz/data-import.html#introduction "r4ds 8.1 & 8.2")                                 | [ðŸ–¥ï¸](slides/week-3.1.qmd)  |                               [ðŸ–¥ï¸](https://youtu.be/YLOaKB8dfF4 "Downloading World Bank data")[ðŸ–¥ï¸](https://youtu.be/XOGXn8IiHK8 "Reading data from a flat file")                                |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,2)`  | Reshape, clean data                                       | `tidyr, dplyr`                                               | `pivot_longer(), mutate()`, `mutate_at()`, `substring()`                                                                                                                            |                                                                                     |                                        [ðŸ“–](https://r4ds.hadley.nz/data-tidy.html "r4ds 6.1 & 6.3")                                         | [ðŸ–¥ï¸](slides/week-3.2.qmd)  |             [ðŸ–¥ï¸](https://youtu.be/ud36szsO9a4 "Reshaping data")[ðŸ–¥ï¸](https://youtu.be/-JT8JSR1z5A "Strings & variable types")[ðŸ–¥ï¸](https://youtu.be/7bgoebbzfKQ "Cleaning var names")             |                                                                 [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 1.1. quiz")                                                                  |
|     [1.2](/modules/module-1.2.html "Module 1.2")      | `r advdate(mon,3)`  | Download data from an API                                 | `wbstats`, `vdemdata`, `dplyr`, `janitor`                    | `wb_data()`, `vdem`, `select_()`, `filter()`, `case_match()`, `round_to_fraction()`                                                                                                 |    [ðŸ“–](https://link.springer.com/article/10.1057/palgrave.ap.5500151 "Norris")     |                                                                                                                                             | [ðŸ–¥ï¸](slides/week-4.1.qmd)  |                           [ðŸ–¥ï¸](https://youtu.be/cBRTP2imt_o "Dowload data from the World Bank")[ðŸ–¥ï¸](https://youtu.be/7CvYTeMP_PU "Filter data and select variables")                            |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,3)`  | Merge data frames, group, summarize and arrange           | `countrycode`, `dplyr` , `readr`                             | `countrycode()`, `left_join()`, `write_csv()`, `group_by()`, `summarize()`, `arrange()`                                                                                             |                                                                                     | [ðŸ“–](https://r4ds.hadley.nz/joins.html#sec-mutating-joins "r4ds, 20.3") [ðŸ“–](https://r4ds.hadley.nz/data-transform.html#groups "r4ds, 4.5") | [ðŸ–¥ï¸](slides/week-4.2.qmd)  | [ðŸ–¥ï¸](https://youtu.be/ZGD0kO_iwAM "Add country codes to data frame")[ðŸ–¥ï¸](https://youtu.be/wNF3ZPneHWw "Merge two data frames")[ðŸ–¥ï¸](https://youtu.be/2nX9p6arQjg "Group, summarize and arrange") |                                 [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 1.2 quiz")[ðŸ§®](/assignments/coding-assignment-1.html "Coding assignment 1")                                  |
|     [2.1](/modules/module-2.1.html "Module 2.1")      | `r advdate(mon,4)`  | Bar charts & histograms                                   | `ggplot2`                                                    | `ggplot()`, `geom_col()`, `geom_histogram()`, `aes()`, `labs()`                                                                                                                     |                                                                                     |        [ðŸ“–](https://r4ds.hadley.nz/data-visualize.html "r4ds, 2")[ðŸ“–](https://r4ds.hadley.nz/communication.html#labels "r4ds, 12.2")        | [ðŸ–¥ï¸](slides/week-5.1.qmd)  |                                                 [ðŸ–¥ï¸](https://youtu.be/hl02sVTyCRA "Bar charts")[ðŸ–¥ï¸](https://youtu.be/LuNDAIQXx9w "Histograms")                                                  |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,4)`  | Line charts & scatter plots                               | `ggplot2`, `scales`                                          | `geom_line()` , `geom_point()`, `geom_smooth()`, `scale_x_log10(),` `label_number()`, `geom_text()`                                                                                 |                                                                                     |                                         [ðŸ“–](https://r4ds.hadley.nz/layers.html "r4ds, 10.1-10.4")                                          | [ðŸ–¥ï¸](slides/week-5.2.qmd)  |                                               [ðŸ–¥ï¸](https://youtu.be/cHos9y261SQ "Line charts")[ðŸ–¥ï¸](https://youtu.be/Cvme3C268wE "Scatter plots")                                                |                                                                  [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 2.1 quiz")                                                                  |
|     [2.2](/modules/module-2.2.html "Module 2.2")      | `r advdate(mon,5)`  | Color schemes                                             | `tidyr`, `colorBlindess`, `dplyr`, `viridis`, `RColorBrewer` | `drop_na()`, `cvdPlot()`, `scale_fill_manual()`, `scale_fill_viridis_d()`, `scale_fill_brewer()`, `scale_color_manual()`, `scale_color_viridis_d()`, `scale_color_brewer`           |     [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/1951731?seq=8 "Lipset")      |                                     [ðŸ“–](https://r4ds.hadley.nz/communication.html#scales "r4ds, 12.4")                                     | [ðŸ–¥ï¸](slides/week-6.1.qmd)  |                                                                       [ðŸ–¥ï¸](https://youtu.be/fBCtSjg_-Ik "Color schemes")                                                                        |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,5)`  | Themes, annotations & interactivity                       | `ggplot2` , `plotly`                                         | `theme_dark()`, `theme_minimal()`, `annotate()`, `geom_hline()`, ``` geom_vline(),``ggplotly() ```, `layout()`                                                                      |                                                                                     |                               [ðŸ“–](https://r4ds.hadley.nz/communication.html#annotations "r4ds, 12.3 & 12.5")                               | [ðŸ–¥ï¸](slides/week-6.2.qmd)  |                          [ðŸ–¥ï¸](https://youtu.be/Le0OJXdsy3o "Themes")[ðŸ–¥ï¸](https://youtu.be/uEpBMgWilXc "Annotations")[ðŸ–¥ï¸](https://youtu.be/T-7jtbcwaJ0 "Interactivity")                          |                                 [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 2.2 quiz") [ðŸ§®](/assignments/coding-assignment-2.html "Coding assignment 2")                                 |
|     [3.1](/modules/module-3.1.html "Module 3.1")      | `r advdate(mon,6)`  | Map data with choropleth maps                             | `rnaturalearth`, `ggplot2`, `ggthemes` , `virids`            | `ne_countries()`, `geom_sf()`, `theme_map()` , `theme()` , `scale_fill_viridis_c()`                                                                                                 |                                                                                     |                                                                                                                                             | [ðŸ–¥ï¸](slides/week-7.1.qmd)  |                                          [ðŸ–¥ï¸](https://youtu.be/HB3PMF93hzs "Choropleth maps")[ðŸ–¥ï¸](https://youtu.be/5RnnGov3Iw4 "Map World Bank data")                                           |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,6)`  | Make a map function                                       |                                                              | `eval()`, `parse()`, `function()`, `source()`                                                                                                                                       |                                                                                     |                                                                                                                                             | [ðŸ–¥ï¸](slides/week-7.2.qmd)  |                                                               [ðŸ–¥ï¸](https://youtu.be/m42vrbEEHT4 "Turn your map into a function")                                                                |                                                                  [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 3.1 quiz")                                                                  |
|     [3.2](/modules/module-3.2.html "Module 3.2")      | `r advdate(mon,7)`  | Upload UCDP data & make a leaflet map                     | `states`, `sf` , `leaflet`                                   | `sfind()`, `st_as_sf()` , `leaflet()`, `addTiles()`, `addMarkers()`, `setView()`                                                                                                    | [ðŸ“–](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctt7s3wz.10 "Ross, Chapter 3") |                                                                                                                                             | [ðŸ–¥ï¸](slides/week-8.1.qmd)  |                                          [ðŸ–¥ï¸](https://youtu.be/If2PwFv90iI "Upload UCDP data")[ðŸ–¥ï¸](https://youtu.be/hHUPqgHRqYU "Make a leaflet map")                                           |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,7)`  | Customize your map                                        | `leaflet`, `htmltools`                                       | `awesomeIcons()`,`addAwesomeMarkers()`, `addProviderTiles()`, `sprintf()`, `lapply()`, `HTML`                                                                                       |                                                                                     |                                                                                                                                             |                            |                                                                     [ðŸ–¥ï¸](https://youtu.be/qLYeSsoDvgs "Customize your map")                                                                     |                                 [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 3.2 quiz") [ðŸ§®](/assignments/coding-assignment-3.html "Coding assignment 3")                                 |
|     [4.1](/modules/module-4.1.html "Module 4.1")      | `r advdate(mon,8)`  | Exploring tabular data                                    | `tidycensus`, `dplyr`, `stringr`, `kableExtra`               | `census_api_key()`, `load_variables()`, `get_acs()`, `rename()`, `rename_with`, `str_remove()`, `kable()`, `slice_max()`, `slice_min()`, `slice_sample()`, `bind_rows()`            |                                                                                     |                                                                                                                                             | [ðŸ–¥ï¸](slides/week-9.1.qmd)  |                   [ðŸ–¥ï¸](Working%20with%20tidycensus "https://www.youtube.com/embed/wo9vZccmqwc")[ðŸ–¥ï¸](https://www.youtube.com/embed/wo9vZccmqwc "Explore data with kableExtra")                   |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,8)`  | Make a `gt` table, make confidence intervals with ggplot2 | `gt` , `ggplot2`                                             | `gt()`, `tab_header()`, `cols_label()`, `fmt_currency()`, `tab_source_note()`, `cols_width()`, `opt_table_font()`, `cols_align()`, `tab_options()`, `gtsave()` , `geom_errorbar()`  |                                                                                     |                                                                                                                                             | [ðŸ–¥ï¸](slides/week-9.2.qmd)  |                           [ðŸ–¥ï¸](https://www.youtube.com/embed/wo9vZccmqwc "Make a gt table")[ðŸ–¥ï¸](https://www.youtube.com/embed/wo9vZccmqwc "Make a coefficient plot")                            |                                                                  [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 4.1 quiz")                                                                  |
|     [4.2](/modules/module-4.2.html "Module 4.2")      | `r advdate(mon,9)`  | Display regression tables                                 | `peacesciencer`, `broom`, `dplyr`                            | `create_stateyears()`, `add_ucdp_acd()`, `add_democracy()`, `add_creg_fractionalization()`, `add_sdp_gdp()`, `add_rugged_terrain()`, `tidy()`, `mutate_if()`, `glm()`, `binomial()` |            [ðŸ“–](https://www.jstor.org/stable/3118222 "Fearon & Laitin")             |                                                                                                                                             | [ðŸ–¥ï¸](slides/week-10.1.qmd) |                                                                                               ðŸ–¥ï¸                                                                                                |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,9)`  | Make regression tables and coefficient plots              | `modelsummary`                                               | `list()`, `modelsummary()`, `modelplot()`, `rev()`                                                                                                                                  |                                                                                     |                                                                                                                                             |                            |                                                                                              ðŸ–¥ï¸ðŸ–¥ï¸                                                                                               | [âœï¸](/project/project-assignment-1.html "Project assignment 1") [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 4.2 quiz") [ðŸ§®](/assignments/coding-assignment-4.html "Coding assignment 4") |
|     [5.1](/modules/module-5.1.html "Module 5.1")      | `r advdate(mon,10)` | Scatter plot app setup, building the UI                   | `dplyr` , `shiny`                                            | `summarize_all()`, `fluidPage()`, `titlePanel()`, `sidebarLayout()`, `sidebarPanel()`, `selectInput()`, `mainPanel()`, `plotOutput()`                                               |                                                                                     |                                                                                                                                             |                            |                                                                                              ðŸ–¥ï¸ðŸ–¥ï¸                                                                                               |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,10)` | Building the server                                       | `shiny`                                                      | `renderPlot()`, `shinyApp()`                                                                                                                                                        |                                                                                     |                                                                                                                                             |                            |                                                                                               ðŸ–¥ï¸                                                                                                |                                                                  [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 5.1 quiz")                                                                  |
|        [5.2](/modules/module-5.2 "Module 5.2")        | `r advdate(mon,11)` | Line chart app setup, building the UI                     | `fredr` , `shiny`                                            | `fredr_set_key()` , `as.Date()` , `Sys.Date()` , `column()`, `wellPanel()`, `helpText()`, `sliderInput()`                                                                           |       [ðŸ“–](https://muse-jhu-edu.proxygw.wrlc.org/article/225602 "Huntington")       |                                                                                                                                             |                            |                                                                                              ðŸ–¥ï¸ðŸ–¥ï¸                                                                                               |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,11)` | Building the server                                       | `fredr` , `shiny`                                            | `reactive()`, `fredr()`, `fred_indicator()`                                                                                                                                         |                                                                                     |                                                                                                                                             |                            |                                                                                               ðŸ–¥ï¸                                                                                                | [âœï¸](/project/project-assignment-2.html "Project assignment 2") [ðŸ“˜](https://blackboard.gwu.edu/ultra/courses/_387298_1/outline "Module 5.2 quiz") [ðŸ§®](/assignments/coding-assignment-5.html "Coding assignment 5") |
|                                                       | `r advdate(mon,12)` | No class, Thanksgiving break                              |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                                             |                            |                                                                                                                                                                                                 |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,12)` | No class, Thanksgiving break                              |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                                             |                            |                                                                                                                                                                                                 |                                                                                                                                                                                                                      |
|     [6.1](/modules/module-6.1.html "Module 6.1")      | `r advdate(mon,13)` | Final project workshop                                    |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                                             |                            |                                                                                               ðŸ–¥ï¸                                                                                                |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,13)` | Final project workshop                                    |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                                             |                            |                                                                                                                                                                                                 |                                                                                                                                                                                                                      |
|     [6.2](/modules/module-6.2.html "Module 6.2")      | `r advdate(mon,14)` | Lightening talks                                          |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                                             |                            |                                                                                               ðŸ–¥ï¸                                                                                                |                                                                                                                                                                                                                      |
|                                                       | `r advdate(wed,14)` | Lightening talks                                          |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                                             |                            |                                                                                                                                                                                                 |                                                                                                                                                                                                                      |
|                                                       | `r advdate(mon,15)` | Lightening talks                                          |                                                              |                                                                                                                                                                                     |                                                                                     |                                                                                                                                             |                            |                                                                                                                                                                                                 |                                                                           [âœï¸](/project/project-assignment-3.html "Project assignment 3")                                                                            |
:::
